### PR TITLE
Create RP05.PEGP_SSDT_Patch.dsl

### PR DESCRIPTION
**Pull request by hla63**
Combine with 
5F514431 to 58514431 _QD1 to XQD1 Rename Patch
5F514435 to 58514435 _QD5 TO XQD5 Rename Patch

tested with msi modern 15 A10M hackintosh (OpenCore)

### CODE REVIEW

**Comment by hla63** [comment]
should work with _OSI(“Linux”)

**Comment by navna** [comment]
Hi. I'm new to all that ACPI stuff, so could you explain in more details what your PR does (or suggests)?

1. Is the provided SSDT file
    - an alternative for DSDT patch
    - or an improvement to existing DSDT patch
    - or a hint/suggestion - since the provided file itself starts with uncompileable (?) lines `Combine with`?
2. Is the problem not in the lack of a device, but just in wrong naming, i. e. `_QD1` instead `XQD1`?
3. Why is the `XDQ1`-call placed in the else branch? Why there is a separate branch for `Darwin`? Which branch relates to `Linux`?
4. Does all of this apply to intermediate methods `_QD2` ... `_QD4`?

**Comment by hla63** [comment]
Sorry some explanations:
That SSDT need to be added to OpenCore boot loader.Works with my msi modern 15.
It's an alternative to keep DSDT untouched for other Os.
If the "Darwin" system (in my case macOS Big Sur) is loaded, this patch applies the renaming of QD1 to XQD1 and QD5 to XQD5 .XQD1 and XQD5 are loaded only if a system is different from "Darwin"
If Darwin was loaded,  If (CondRefOf (^^^RP05.PEGP)) was applied for QD1 and QD5 as separate SSDT Table.

5F514431 was _QD1 Hex value conversion
58514431 was XQD1 Hex value conversion
5F514435 was _QD5 Hex value conversion
58514435 was XQD5 Hex value conversion
Acpi patch

I'm not sure if this method could be use with linux.
DSDT qd1_qd5 renamed

**Comment by navna** [comment]
TY for explanation.

If I understand correctly:
1. In DSDT just rename the methods without touching anything else.
2. Use SSDT to patch original methods for specific OSes.

I will try to check this on Linux this weekend.

**Comment by hla63** [comment]
That's right.

**Comment by navna** [comment]
It seems to work under Linux.

But since `_OSI("Linux")` [is deprecated](https://www.kernel.org/doc/html/latest/firmware-guide/acpi/osi.html) (and `_OSI("Darwin")` is ignored by default), it is probably better to use something like `_OSI("Linux-OEM-Patchname")` with the corresponding `acpi_osi` kernel parameter.

On the other hand, I want to minimize the number of additional arguments in the kernel command line for Linux-only machines.

I will think about how to organize it better and add rename patches and update README a bit later.

**Pull request merged**
